---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the kerberos packages 
  yum: name={{ item }} state=present
  with_items: kerberos_server_redhat_pkg

- name: Copy the kdc configuration file 
  template: src=kdc.conf.j2 dest=/var/kerberos/krb5kdc/kdc.conf
  notify: 
   - restart kerberos

- name: Copy the kdc acl configuration file 
  template: src=kadm5.acl.j2 dest=/var/kerberos/krb5kdc/kadm5.acl
  notify: 
   - restart kerberos

- name: Copy the client configuration file 
  template: src=krb5.conf.j2 dest=/etc/krb5.conf

- name: Link /dev/random to /dev/urandom
  file: path=/dev/random src=/dev/urandom state=link force=yes

- name: Create the initial kerberos database
  shell: echo -e "{{ kerberos_server_master_db_pass }}\n{{ kerberos_server_master_db_pass }}" | kdb5_util create -s; touch /var/kerberos/db_created creates=/var/kerberos/db_created

# Start the kerberos services 
- name: Start krb5kdc service
  service: name=krb5kdc state=started enabled=yes

# if /var/kerberos/krb5kdc/kpropd.acl exists, do not try to start kadmin on this host as it is probably a slave
- name: Check if slave (kpropd.acl exists)
  stat: path=/var/kerberos/krb5kdc/kpropd.acl
  register: st
- name: Start kadmin service if not slave
  service: name=kadmin state=started enabled=yes
  when: st.stat.exists == False
